=== marei94203729/vue/src/main/resources/handler.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!ELEMENT configuration (condition ?|outputFiled ?)>
        <!ELEMENT condition (filter *)>
        <!ELEMENT filter (property *|columnset?)><!ATTLIST filter name CDATA ""><!ATTLIST filter class CDATA "" #REQUIRED><!ATTLIST filter assign CDATA "" #IMPLIED>
        <!ELEMENT property (filter ?|columnset ?)><!ATTLIST property name CDATA ""><!ATTLIST property enable (true|false)><!ATTLIST property label CDATA "" #IMPLIED > <!ATTLIST property order CDATA#IMPLIED >
        <!ATTLIST property tag (custom|number|text|select|select3|date)><!ATTLIST property class CDATA #IMPLIED ><!ATTLIST property size CDATA "" #IMPLIED >
        <!ATTLIST property method CDATA #IMPLIED >
        <!ELEMENT columnset (column *)>
        <!ELEMENT column ANY>
        <!ATTLIST column sortable (custom|false) #IMPLIED><!ATTLIST column fixed (true|false)#IMPLIED><!ATTLIST column label CDATA "" #REQUIRED><!ATTLIST column order CDATA#IMPLIED ><!ATTLIST column element (true|false)#IMPLIED>
        <!ATTLIST column width CDATA "" #REQUIRED><!ATTLIST column prop CDATA "" #REQUIRED><!ATTLIST column tooltip (true|false)>
        <!ELEMENT outputFiled (fields *)>
        <!ELEMENT fields (field ?)>
        <!ATTLIST fields  name CDATA "" #REQUIRED><!ATTLIST fields class CDATA "" #REQUIRED><!ATTLIST fields assign CDATA "" #REQUIRED>
        <!ELEMENT field ANY>
        <!ATTLIST field  name CDATA "" #REQUIRED><!ATTLIST field label CDATA "" #REQUIRED><!ATTLIST field order CDATA#IMPLIED ><!ATTLIST field size CDATA "" #IMPLIED ><!ATTLIST field require (true|false)><!ATTLIST field note CDATA "" #IMPLIED>
        <!ATTLIST field tag (number|text|select|date|select1|select2|select3|label|rich)><!ATTLIST field class CDATA #IMPLIED><!ATTLIST field method CDATA #IMPLIED >

=== marei94203729/vue/src/main/resources/handler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "handler.dtd">
<configuration>
    <condition>
        <filter name="refundAudit" class="RefundAuditService"  assign="RefundAudit">
            <property order="1" name="docno" label="单据" enable="true" tag="text"></property>
            <property order="2" name="cOrigId" label="分店" enable="true" tag="custom">
                <filter name="store" class="StoreService"  assign="Store">
                    <property order="1" name="code" label="分店代码" enable="true" tag="text" size="15"></property>
                    <property order="2" name="name" label="分店名称" enable="true" tag="text" size="35"></property>
                    <property order="3" name="description" label="分店全称" enable="true" tag="text" size="52"></property>
                    <property order="4" name="areaName" label="所属大区" enable="true" tag="text" size="20"></property>
                    <property order="5" name="custName" label="加盟商" enable="true" tag="text" size="10"></property>
                    <property order="6" name="partNo" label="部次号" enable="true" tag="text" size="50"></property>
                    <property order="7" name="blockName" label="分支机构" enable="true" tag="text" size="50"></property>
                    <property order="8" name="salerName" label="所属销售" enable="true" tag="text" size="50"></property>
                    <property order="9" name="branchName" label="分公司" enable="true" tag="text" size="50"></property>
                    <property order="10" name="isStop" label="关店标志" enable="true" tag="select" class="com.cros.vue.service.StoreService" method="getIsStop"></property>
                    <property order="11" name="isactive" label="可用" enable="true" tag="select" class="com.cros.vue.service.StoreService" method="getIsActive"></property>
                </filter>
                <columnset>
                    <column order="1"  sortable="custom" label="分店代码" width="100" prop="code" tooltip="true"></column>
                    <column order="2"  sortable="custom" label="分店名称" width="100" prop="name" tooltip="true"></column>
                    <column order="3"  sortable="custom" label="分店全称" width="100" prop="description" tooltip="true"></column>
                    <column order="4"  sortable="custom" label="部次号" width="100" prop="partNo" tooltip="true"></column>
                    <column order="5"  sortable="custom" label="加盟商代码" width="100" prop="custCode" tooltip="true"></column>
                    <column order="6"  sortable="custom" label="加盟商" width="100" prop="custName" tooltip="true"></column>
                    <column order="7"  sortable="custom" label="分支机构" width="100" prop="blockName" tooltip="true"></column>
                    <column order="8"  sortable="custom" label="分公司" width="100" prop="branchName" tooltip="true"></column>
                    <column order="9"  sortable="custom" label="所属大区" width="100" prop="areaName" tooltip="true"></column>
                    <column order="9"  sortable="custom" label="所属销售" width="100" prop="salerName" tooltip="true"></column>
                </columnset>
            </property>
            <property order="3" name="retsaletype" label="退货类型" enable="true" tag="select" class="com.cros.vue.service.RefundAuditService" method="getRetType"></property>
            <property order="4" name="saleType" label="销售类型" enable="true" tag="select" class="com.cros.vue.service.RefundAuditService" method="getSaleType"></property>
            <property order="5" name="status" label="审核状态" enable="true" tag="select" class="com.cros.vue.service.RefundAuditService" method="getRetStatus"></property>
            <property order="6" name="billdate" label="单据日期" enable="true" tag="date"></property>
            <property order="7" name="creationdate" label="创建时间" enable="true" tag="date"></property>
            <property order="8" name="statustime" label="提交时间" enable="true" tag="date"></property>
            <columnset>
                <column order="1" element="true"  sortable="custom" label="单号" width="150" prop="docno" tooltip="true"></column>
                <column order="2" element="true" sortable="custom" label="单据日期" width="100" prop="billdate" tooltip="true"></column>
                <column order="3" element="true" sortable="custom" label="库房代码" width="100" prop="storeCode" tooltip="true"></column>
                <column order="4" element="true" sortable="custom" label="库房名称" width="100" prop="storeName" tooltip="true"></column>
                <column order="5" element="true" sortable="custom" label="机构代码" width="100" prop="blockCode" tooltip="true"></column>
                <column order="6" element="true" sortable="custom" label="机构名称" width="110" prop="blockName" tooltip="true"></column>
                <column order="7" element="true" sortable="custom" label="分店代码" width="100" prop="lcCode" tooltip="true"></column>
                <column order="8" element="true" sortable="custom" label="分店名称" width="100" prop="lcName" tooltip="true"></column>
                <column order="9" element="true" sortable="custom" label="顾客代码" width="100" prop="custCode" tooltip="true"></column>
                <column order="10" element="true" sortable="custom" label="顾客名称" width="100" prop="custName" tooltip="true"></column>
                <column order="11" element="true" sortable="custom" label="审核状态" width="100" prop="statusName" tooltip="true"></column>
                <column order="12" element="true" sortable="custom" label="销售类型" width="100" prop="saleName" tooltip="true"></column>
                <column order="13" element="true" sortable="custom" label="单据种类" width="100" prop="billName" tooltip="true"></column>
                <column order="14" element="true" sortable="custom" label="退货类型" width="100" prop="retsaleName" tooltip="true"></column>
                <column order="15" element="true" sortable="custom" label="退货量" width="100" prop="totQty" tooltip="true"></column>
                <column order="16" element="true" sortable="custom" label="退货金额" width="100" prop="totAmtActual" tooltip="true"></column>
                <column order="17" element="true" sortable="custom" label="流水号" width="120" prop="billno" tooltip="true"></column>
                <column order="18" element="true" label="查看" width="180"  tooltip="false"></column>
            </columnset>
        </filter>
        <filter name="accountAmt" class="AccountAmtService"  assign="AccountAmt">
            <property order="1" name="cOrigId" label="分店" enable="true" tag="custom">
                <filter name="store" class="StoreService"  assign="Store">
                    <property order="1" name="code" label="分店代码" enable="true" tag="text" size="15"></property>
                    <property order="2" name="name" label="分店名称" enable="true" tag="text" size="35"></property>
                    <property order="3" name="description" label="分店全称" enable="true" tag="text" size="52"></property>
                    <property order="4" name="areaName" label="所属大区" enable="true" tag="text" size="20"></property>
                    <property order="5" name="custName" label="加盟商" enable="true" tag="text" size="10"></property>
                    <property order="6" name="partNo" label="部次号" enable="true" tag="text" size="50"></property>
                    <property order="7" name="blockName" label="分支机构" enable="true" tag="text" size="50"></property>
                    <property order="8" name="salerName" label="所属销售" enable="true" tag="text" size="50"></property>
                    <property order="9" name="branchName" label="分公司" enable="true" tag="text" size="50"></property>
                    <property order="10" name="isStop" label="关店标志" enable="true" tag="select" class="com.cros.vue.service.StoreService" method="getIsStop"></property>
                    <property order="11" name="isactive" label="可用" enable="true" tag="select" class="com.cros.vue.service.StoreService" method="getIsActive"></property>
                </filter>
                <columnset>
                    <column order="1"  sortable="custom" label="分店代码" width="100" prop="code" tooltip="true"></column>
                    <column order="2"  sortable="custom" label="分店名称" width="100" prop="name" tooltip="true"></column>
                    <column order="3"  sortable="custom" label="分店全称" width="100" prop="description" tooltip="true"></column>
                    <column order="4"  sortable="custom" label="部次号" width="100" prop="partNo" tooltip="true"></column>
                    <column order="5"  sortable="custom" label="加盟商代码" width="100" prop="custCode" tooltip="true"></column>
                    <column order="6"  sortable="custom" label="加盟商" width="100" prop="custName" tooltip="true"></column>
                    <column order="7"  sortable="custom" label="分支机构" width="100" prop="blockName" tooltip="true"></column>
                    <column order="8"  sortable="custom" label="分公司" width="100" prop="branchName" tooltip="true"></column>
                    <column order="9"  sortable="custom" label="所属大区" width="100" prop="areaName" tooltip="true"></column>
                    <column order="10"  sortable="custom" label="所属销售" width="100" prop="salerName" tooltip="true"></column>
                </columnset>
            </property>

            <property order="2" name="billdate" label="日 期" enable="true" tag="date"></property>
            <columnset>
                <column order="1" element="true"  sortable="custom" label="客户代码" width="100" prop="code" tooltip="true"></column>
                <column order="2" element="true" sortable="custom" label="客户简称" width="100" prop="name" tooltip="true"></column>
                <column order="3" element="true" sortable="custom" label="客户全称" width="120" prop="description" tooltip="true"></column>
